---
title: Term Project Proposal
subtitle: 16:540:94:01, Adv Topics in I.E. - Data Mining I

date: 2025-11-15
date-format: iso
lang: en-US

author:
  - name: Daniel Moore
    email: daniel.l.moore@rutgers.edu
    roles: writing, research
    corresponding: true
    affiliation: 
      - name: Rutgers University
        city: Piscataway
        state: NJ
        url: www.rutgers.edu

bibliography: references.bib  

abstract: We use some kind of clustering to improve the model selection for the inclusion of aggregated DERs in the SO's optimizaiton problems.

---

# Background

Distributed Energy Resources (DERs) deployment is growing in their individual capacity and proliferation at both grid scale and house-level systems. While the benefit of the grid-scale elements are already being realized by inclusion in the energy grid operational planning, the house-level possess untapped potential flexibility.  Some house-level systems include electric vehicles (EVs), battery storage (BS), roof top photovoltaic cells (PV), and thermostatically-controlled loads (TCLs). For the most part, these DERs respond only to the flat, retail electricity rate or in some select areas, a simple time-of-use (TOU) tarriff system. This is a market shortfall because the DERs could exhibit price-responsive behavior if they participated in the wholesale electricty market. They could be incentivized to shift loads off, or inject power during, peak-price times. This would reduce reliance on peaker-plants which are known to be the most costly, dirtiest, and associated with negative public-health outcomes. The benefits can be highly nonlinear as the time of day that power is produced or consumed could mean that the usage is effecting the baseload (negligible impact) or maybe the annual-peak load (substantial impact), or something in between.

While the potential net flexibility of the DERs could have a substantial impact, they are too numerous and individually insignificant for the System Operator (SO) to include in their planning and dispatch optimization problems. This is exacerbated by the fact that their feasible dispatch region is typically non-convex. A common solution is for a DER Aggregator (DERA) to represent a portfolio of DERs to the SO as a virtual battery. This aggregates the non-convex feasible dispatch regions with relatively insignificant flexibility into a linear model that can be direclty incorporated into the SO's optimization problem. This convex approximation is acceptable because aggregating the individual, non-convex sets will lead to a set that approaches convexity as the number of aggregated assets increases. Under this scheme, the DERA must carefully design the parameters of the virtual battery model which are the time-dependent power, state-of-charge, and ramping bounds so that it closely matches the true feasible region of the aggregate. This is not straightforward. It is impractical to aggregate the true feasible region from the individual DERs because amassing and maintaining up-to-date infromation would be a massive clerical burden. Even if this was practical to obtain, the DERA would need to calculate the convex-hull of this non-convex set which again brings us to computational intractability.

A strong alternative is to infer the parameters from past observations of price-responsive behavior. Assuming that this data can be obtained by observing the DERs' aggregated resposne for some period of time, we use Data-Driven Inverse Optimization (DDIO) to infer the parameters of a virtual battery model which would lead to the same decisions as the aggregated power usage. However, the virtual battery parameters need to change from day to day because the feasible region of individual DERs such as TCLs (or BS which are used to run household HVAC, for example) are significantly altered by the weather. While we can use IO to infer the parameters for a given day ex post facto, this provides no utility because the DERA needs to submit the virtual battery model to the SO before the planning problems are solved rather than after the events have past.

What we really want is a single set of parameters which will closely match observed price-responsive behavior over a number of days. Again, we run into computational tractability issues because the IO formulation is a bilevel program where we must enforce complementary slackness. To avoid bilinear terms, we introduce binary variables with $big-M$ for each constraint to enforce complementary slackness. We employ progressive hedging to overcome this by solving for one day at a time (which is tractable), but penalizing for deviation from the average parameters over a select set of days. After solving for parameters for each day in the set, the consensus is updated and the process is iterated until one some termination criteria is met (the days have converged on a consensus, the consensus change has effictively stopped changing from one iteration to the next, or a maximum number of iterations is reached). This problem is still computationally intensive, but is highly parallelizable as each day in the iteration can be solved independently.

This brings us to the final question the DERA must answer: for "tomorrow", $D+1$, which set of days from days in $d=1 \ldots D$ should be used to form a conensus using the progressive hedging, inverse optimization method? Currently, we cluster all days based on their temperature profile using K-Means clustering into $K=6$. We then use the methodology outlined above to obtain a consensus parameterization for each cluster, $\overline{x}^{(c)} \in \mathbb{R}^{6T}\ \forall c \in K$. $D+1$ is assigned to cluster $c$ and the consensus for that cluster is submitted to the SO as the parameterization for that day.

$$
\overline{x}^{(D+1)} = \overline{x}^{(c(D+1))}
$$ {#eq-d-plus-one-uses-days-clusters-consensus}

While this provides an intuitive and simple to implement method which captures some aspect of the relationship of weather to the feasible region, it might be overly simplistic. We seek a method for the DERA to reduce their risk exposure by better selecting the set of historical days, $\mathcal{H}$ used to obtain a consensus for $D+1$. A better classification system might be obtained with more external features and or a more sophisticated classification system.

We want to explore how we can select the optimal (or improved) $\mathcal{H}$ upon which to base $\overline{x}^{(D+1)}$. We will measure the difference relative to the existing system by the power usage discrepancy for each day.

# Data Sets

One year of hourly weather data for Piscataway, NJ was obtained from "Visual Crossings".

One year of day-ahead (DA) locational marginal pricing (LMP) data for Piscataway, NJ was obtained from the Pennsylvania, Jersey, Maryland (PJM) Regiona Transmission Operator (RTO).

These were combined and passed to a set of DER models to generate a synthetic dataset of aggregated DER price-reponsive power usage behavior.

# Virtual Battery Model

$$
\begin{split}
\arg\min_{\bf{x} \in \mathbb{R}^{6T}} & \bf{c}^\top \bf{p} \\
s.t.\ & \bf{G} \bf{p} \le \bf{x}
\end{split}
$$ {#eq-vb-model}